---
name: 🔶 Test Sync to Jira

run-name: >
  TEST Sync to Jira -
  ${{ github.event_name == 'issue_comment' && 'Issue Comment' ||
      github.event_name == 'pull_request' && 'Created Pull Requests' ||
      github.event_name == 'schedule' && 'Scheduled Unsynced Pull Requests' ||
      github.event_name == 'issues' && 'New Issue' ||
      github.event_name == 'workflow_dispatch' && 'Manual Sync' }}

on:
  issues: {types: [opened]}
  issue_comment: {types: [created, edited, deleted]}
  pull_request: {types: [opened]}
  schedule: [cron: '0 12 * * *']
  workflow_dispatch:
    inputs:
      action: {description: 'Action to be performed', required: true, default: 'mirror-issues'}
      issue-numbers: {description: 'Issue numbers to sync (comma-separated)', required: true}

jobs:
  sync-to-jira:
    name: >
      Sync to Jira -
      ${{ github.event_name == 'issue_comment' && 'Issue Comment' ||
          github.event_name == 'pull_request' && 'Created Pull Requests' ||
          github.event_name == 'schedule' && 'Scheduled Unsynced Pull Requests' ||
          github.event_name == 'issues' && 'New Issue' ||
          github.event_name == 'workflow_dispatch' && 'Manual Sync' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run synchronization to Jira
        uses: tomassebestik/github-action-testing@master
        with:
          cron_job: true
          jira_project: 'TEST'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
